### ISSUE TITLE
Class Not Found

### ISSUE THREAD

**Issue by JorginoGC** [danieldevine/elephant-bird#3]
In all classes it gives me the following error when trying to use them (not found):

**Chorme**
![image](https://user-images.githubusercontent.com/66069708/103153627-249d0680-4792-11eb-9d02-9cc5fd1b3493.png)

**Visual Studio**
![image](https://user-images.githubusercontent.com/66069708/103153609-0a632880-4792-11eb-9ad3-a22661353396.png)

**Comment by danieldevine** [comment]
Hi,

I don't think this is an issue with the library. 
Are you sure that you are autoloading correctly? 

If you think it's something specific to the library you'll need to give me some more detail about the way you're autoloading classes in your project.

**Comment by JorginoGC** [comment]
i used $ `composer require coderjerk/elephant-bird` to install

**Comment by danieldevine** [comment]
Yes, that is how you install the library.... however It's then up to you to autoload the classes in your project.

I would advise you to read the following: 

[https://getcomposer.org/doc/01-basic-usage.md#autoloading](https://getcomposer.org/doc/01-basic-usage.md#autoloading)

you should also  probably run  ``` composer dump-autoload ```  when you add a new dependency via composer. 

This probably isn't an issue with the library, this issue is most likely with how your project is configured.
